### ISSUE TITLE
Reusing paths between standalone module and development server configuration

### ISSUE THREAD

**Issue by hheimbuerger** [etianen/django-require#70]
I'm using django-require with a single `REQUIRE_STANDALONE_MODULES` and a build profile. In the build profile, I set the `paths` configuration like this:

    paths: {
        "jquery": "libs/jquery-1.12.1"
    },

Now when I run the app in DEBUG mode (i.e. without having built the JS file and with require.js instead of almond.js), it doesn't use the build profile and can't find the `jquery` dependency.

Is there an elegant way to reuse the paths between the two build configurations?

It does work when using something like this, but I'd prefer to avoid the duplication:

    {% require_module 'entrypoint' %}
    <script>
        requirejs.config({
            paths: {
                "jquery": "libs/jquery-1.12.1"
            }
        });
    </script>

**Comment by etianen** [comment]
I do not believe there is an elegant way to do this. I'd honestly recommend
keeping requirejs configuration incredibly simple and avoiding path
configuration at all. RequireJS can end up having incredibly complex
configs, most of which can be avoided by:

1. Place your entry point module at the root of your module hierarchy.
2. Refer to everything by the real module paths.

Otherwise, you rapidly fall down a rabbit hole of configuration from which
there is no return.

**Comment by hheimbuerger** [comment]
@etianen I see, thanks for the feedback!

Is it really realistic to have no (shared) configuration at all, though? I'm thinking of the `shim`s I currently need for Bootstrap for example. Doesn't sound like I can completely get rid of these aspects.

Do you have no `app.build.js` and no `requirejs.config(…)` at all in your projects?

**Comment by etianen** [comment]
When I've needed a complex configuration, I've omitted the standalone
modules, and used the requirejs main libraries in production. At that
point, you can define your config in a separate file, referenced
by mainConfigFile in your build profile, and imported by your HTML page.

**Comment by hheimbuerger** [comment]
@etianen Not sure I'm following completely. Are you saying that you didn't use r.js at all? No `REQUIRE_STANDALONE_MODULES`? Did you use another tool for concatenating?

Is there an example of this somewhere for me to better grasp the concept?

**Comment by etianen** [comment]
I'm saying that a good way of sharing config is to put all the config in
your main.js file using require.config(), then use mainConfigFile in your
build profile to reference your main file.

I originally meant to say that I'd use REQUIRE_BUILD_PROFILE instead of
REQUIRE_STANDALONE_MODULES, but now I think about it, the above technique
would probably work with standalone modules too.

**Comment by hheimbuerger** [comment]
I don't fully understand your answer, but I've just gotten into the habit of always maintaining both my `app.build.js` as well as the `require.config()` setup in my `base.html`, so I'm closing this issue.
